class Languages {
  static const Map<String, String> ptBr = {
    "new": "Novo",
    "used": "Usado",
    "undefined_serial": "Serial indefinido",
    "undefined_model": "Modelo indefinido",
    "undefined_cost": "Custo indefinido",
    "model": "Modelo",
    "company_group": "Grupo empresarial",
    "branch_office": "Filial",
    "current_life_cycle": "Ciclo de vida atual",
    "times_retreaded": "Vezes recauchutado",
    "max_retreads_expected": "Máximo de recauchutagens esperado",
    "recommended_pressure": "Pressão recomendada",
    "current_pressure": "Pressão atual",
    "dot": "DOT",
    "purchase_cost": "Preço",
    "status": "Status",
    "tire_size": "Tamanho do pneu",
    "width": "Largura",
    "height": "Altura",
    "rim": "Aro",
    "make": "Fabricante",
    "current_retread": "Recauchutagem atual",
    "name": "Nome",
    "grooves_quantity": "Quantidade de sulcos",
    "tread_depth": "Profundidade do sulco",
    "retread_cost": "Custo de recauchutagem",
    "disposal": "Descarte",
    "description": "Descrição",
    "disposal_images": "Imagens do descarte",
    "images": "Imagens",
    "general_information": "Informações gerais",
    "retread": "Recauchutagem",
    "serial": "Serial",
    "specifications": "Especificações",
    "health": "Saúde",
    "disposal_reason": "Razão do descarte",
    "visualize_image": "Visualizar imagem",
  };

  static const Map<String, String> enUs = {
    "new": "New",
    "used": "Used",
    "undefined_serial": "Undefined serial",
    "undefined_model": "Undefined model",
    "undefined_cost": "Undefined cost",
    "model": "Model",
    "company_group": "Company group",
    "branch_office": "Branch office",
    "current_life_cycle": "Current life cicle",
    "times_retreaded": "Time retreaded",
    "max_retreads_expected": "Max retreads expected",
    "recommended_pressure": "Recommended pressure",
    "current_pressure": "Current pressure",
    "dot": "DOT",
    "purchase_cost": "Purchase cost",
    "status": "Status",
    "tire_size": "Tire size",
    "width": "Width",
    "height": "Height",
    "rim": "Rim",
    "make": "Make",
    "current_retread": "Current retread",
    "name": "Name",
    "grooves_quantity": "Grooves quantity",
    "tread_depth": "Tread depth",
    "retread_cost": "Retread cost",
    "disposal": "Disposal",
    "description": "Description",
    "disposal_images": "Disposal images",
    "images": "Images",
    "general_information": "General information",
    "retread": "Retread",
    "serial": "Serial",
    "specifications": "Specifications",
    "health": "Health",
    "disposal_reason": "Disposal reason",
    "visualize_image": "Visualize image",
  };
}
